name: Auto commit
on:
  push:
    branches:
      - master
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: Commit changes
        run: |
          git config --local user.email "73228642+antono4@users.noreply.github.com"
          git config --local user.name "antono4"
          git add -A
          git commit -m "chore(bot): probe auto commit"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          directory: "."
          github_token: ${ secrets.GITHUB_TOKEN }
